routes/web.php
<?php

Route::get('/', 'EstateCatalogController@index')->name('index');
Route::get('/search', 'EstateCatalogController@search')->name('ad.search');
Route::get('/object-{id}', 'EstateCatalogController@showAd')->name('ad.show');

Route::get('/category/{alias}', 'EstateCatalogController@showCategory')
    ->where('alias', '[A-Za-z/-]+')
    ->name('category.show');
Route::get('/catalog/sold', 'EstateCatalogController@sold')->name('category.sold');

Route::get('/articles', 'ArticleController@index')->name('articles.index');

Route::get('/catalog/sale', function() {
    return view('site/special/sale', ['meta_title' => 'Продажа бизнеса']);
})->name('category.sale');

Route::get('/reviews', 'ReviewController@index')->name('reviews.index');
Route::get('/jobs', 'JobsController@index')->name('jobs.index');
Route::get('/jobs/{id}', 'JobsController@show')->name('jobs.show');

Route::group([
    'as' => 'special.',
], function () {
    Route::get('/modal/{key}', 'ServicePageController@showModal')->name('modal');
    Route::post('/form/{key}', 'FromHandlerController@send')->name('form.handler');

    /**
     * Special page resolved by router name
     * All special page used template from site/special/[route_name]
     */
    Route::get('/contacts', 'ServicePageController@special')->name('contacts');
    Route::get('/about-us', 'ServicePageController@special')->name('about');

    /** Business services */
    Route::get('/poluchenie-vypisok', 'ServicePageController@special')->name('extracts');
    Route::get('/poisk-biznesa', 'ServicePageController@special')->name('business-search');
    Route::get('/proverka-riskov', 'ServicePageController@special')->name('risk-check');
    Route::get('/soprovozhdenie-sdelki', 'ServicePageController@special')->name('transaction-support');
    Route::get('/registraciya-yuridicheskih-lic', 'ServicePageController@special')->name('registration-entities');

    /** Other service page */
    Route::get('/services', 'ServicePageController@special')->name('other-service');
});

Auth::routes();

/* admin management routes */

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => [
        'auth'
    ]
], function () {

    App\Http\Controllers\Admin\CustomerCallingController::route();
    App\Http\Controllers\Admin\DashboardController::route();
    App\Http\Controllers\Admin\DeclarationController::route();
    App\Http\Controllers\Admin\PlaneController::route();

    Route::resource('articles', 'ArticlesController');
    Route::resource('categories', 'CategoriesController');

    Route::resource('users', 'UsersController');
    Route::get('users/{id}/roles', 'UsersController@showRoles')->name('users.roles');
    Route::put('users/{id}/roles', 'UsersController@updateRoles')->name('users.updateRoles');

    Route::resource('roles', 'RolesController');

    //TODO: exclude show resource

    App\Http\Controllers\Admin\EstateController::route();

    Route::get('customer-calling-history/{id}/event/{event_id}', 'CustomerCallingController@editEvent')->name('customer.calling.event');
    Route::put('customer-calling-history/{id}/event/{event_id}', 'CustomerCallingController@updateEvent')->name('customer.calling.event.update');
    Route::get('customer-calling-history/{id}/event/{event_id}/delete', 'CustomerCallingController@deleteEvent')->name('customer.calling.event.delete');

    Route::get('customer-calling-history/{id}/comments', 'CustomerCallingController@comments')->name('customer.calling.comments');
    Route::post('customer-calling-history/{id}/comments', 'CustomerCallingController@addComment')->name('customer.calling.comments.add');
    Route::get('customer-calling-history/{id}/comments/{commentId}', 'CustomerCallingController@editComment')->name('customer.calling.comments.edit');
    Route::put('customer-calling-history/{id}/comments/{commentId}', 'CustomerCallingController@updateComment')->name('customer.calling.comments.update');
    Route::get('customer-calling-history/{id}/comments/{commentId}/delete', 'CustomerCallingController@deleteComment')->name('customer.calling.comments.delete');

    Route::resource('review', 'ReviewController');
    Route::resource('jobs', 'JobsController');

    App\Http\Controllers\Admin\DirectoryController::route();

    Route::get('directory/{index}/item/{id}', 'DirectoryController@item')->name('directory.item');

    Route::get('/review', 'ReviewController@index')->name('review.index');
    Route::delete('/review/{id}', 'ReviewController@destroy')->name('review.destroy');

    Route::get('/jobs', 'JobsController@index')->name('jobs.index');
    Route::get('/jobs/{id}', 'JobsController@show')->name('job.show');
    Route::get('/jobs/{id}/delete', 'JobsController@destroy')->name('jobs.destroy');

    Route::get('documents', 'DocumentsController@index')->name('documents.index');
    Route::post('documents', 'DocumentsController@upload')->name('documents.upload');
    Route::get('documents/delete', 'DocumentsController@delete')->name('documents.delete');

    Route::get('forms/', 'FormReportController@index')->name('form.index');
    Route::get('forms/{form_id}', 'FormReportController@show')->name('form.show');

    Route::get('forms/{estate}/comments', 'FormReportController@comments')->name('form.comments');
    Route::post('forms/{estate}/comments', 'FormReportController@addComment')->name('form.comments.add');
    Route::get('forms/{estate}/comments/{commentId}', 'FormReportController@editComment')->name('form.comments.edit');
    Route::put('forms/{estate}/comments/{commentId}', 'FormReportController@updateComment')->name('form.comments.update');
    Route::get('forms/{estate}/comments/{commentId}/delete', 'FormReportController@deleteComment')->name('form.comments.delete');
});

Route::get('/image/', 'ImageGeneratorController@generate');
Route::get('/image/flush', 'ImageGeneratorController@flush');

Route::post('basket', 'FileBasketController@putFile')->name('basket');
Route::delete('basket', 'FileBasketController@dropFile');

Route::get('{url}', 'ArticleController@show')->name('articles.show')
    ->where('url', '.*');

app/Jobs.php
<?php


namespace App;

use App\Traits\BelongsToUser;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Jobs extends Model
{
    protected $fillable = [
      'department_id',
      'job_name',
      'job_description',
      'is_published',
    ];

    public function departments()
    {
        return $this->hasOne('App\Departments', 'id', 'department_id');
    }

    public function getIsPublishedAttribute()
    {
        return is_null($this->attributes['deleted_at'] ?? null) && !is_null($this->attributes['published_at'] ?? null);
    }

    public function setIsPublishedAttribute($value)
    {
        $value = (bool)$value;

        if ($this->getIsPublishedAttribute() !== $value) {
            $this->attributes['published_by'] = $value ? \Auth::user()->id : null;
            $this->attributes['published_at'] = $value ? Carbon::now() : null;
        }

    }
}

app/Http/Controllers/Admin/JobsController.php
<?php


namespace App\Http\Controllers\Admin;

use App\Jobs;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class JobsController extends Controller
{
    public function index()
    {
        $jobs = Jobs::paginate(20);

        return view('admin/jobs/list', [
          'jobs' => $jobs,
        ]);
    }

    public function create(Request $request)
    {
        return view('admin/jobs/create', [
          'jobs' => $request
        ]);
    }

    public function edit($id)
    {
        $jobs = Jobs::findOrFail($id);

        return view('admin/jobs/edit', [
          'jobs' => $jobs
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
          'department_id' => 'required',
          'job_name' => 'required',
          'job_description' => 'required',
        ]);

        $jobs = Jobs::create($request->all());
        return redirect()->route('admin.jobs.index')
          ->with('status', 'Запись успешно обновлена')
          ->with('new_jobs_id', $jobs->id);
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'department_id' => 'required',
          'job_name' => 'required',
          'job_description' => 'required',
        ]);

        $jobs = Jobs::findOrFail($id);

        $jobs->update($request->all());

        return redirect()->route('admin.jobs.index')
          ->with('status', 'Запись успешно обновлена')
          ->with('new_jobs_id', $jobs->id);
    }

    public function destroy($id)
    {
      Jobs::findOrFail($id)->delete();

      return redirect()->route('admin.jobs.index')
          ->with('status', 'Запись успешло удалена');
    }
}

app/Http/Controllers/JobsController.php
<?php

namespace App\Http\Controllers;

use App\Departments;
use App\Jobs;
use Illuminate\Database\Eloquent\Builder;

class JobsController extends Controller
{
    public function index()
    {
        $departments = Departments::with(['jobs'])
            ->whereHas('jobs', function (Builder $builder){
                $builder->whereNotNull('published_at');
            })
            ->get();

        return view('site/jobs/list', [
          'departments' => $departments,
        ]);
    }

    public function show($id)
    {
        $job = Jobs::findOrFail($id);

        return view('site/jobs/job', [
          'job' => $job
        ]);
    }
}

resources/views/admin/jobs/create.blade.php
@extends('admin/layout', [
'title' => 'Новая вакансия'
])

@section('content')
  {!! Form::open(['action' => ['Admin\JobsController@store'], 'method'=>'POST']) !!}

  @include('admin/jobs/form', ['jobs' => $jobs])

  {{ Form::submit('Добавить',['class'=>'btn btn-success'])}}

  {!! Form::close() !!}
@stop

resources/views/admin/jobs/edit.blade.php
@extends('admin/layout', [
'title' => 'Вакансия: ' . $jobs->job_name
])

@section('content')
  {!! Form::model($jobs, ['action' => ['Admin\JobsController@update', $jobs->id], 'method'=>'PUT']) !!}

  @include('admin/jobs/form', ['jobs' => $jobs])

  {{ Form::submit('Сохранить',['class'=>'btn btn-success'])}}

  {!! Form::close() !!}
@stop

resources/views/admin/jobs/form.blade.php
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <label>Отдел</label>
      @include('/admin/parts/directory' , ['name' => 'department_id', 'directoryIndex' => 'departments'])
      @if ($errors->has('title'))
        <div class="alert alert-danger">
          {{ $errors->first('title') }}
        </div>
      @endif
    </div>
    <div class="form-group">
      <label>Название вакансии</label>
      {!! Form::input('text', 'job_name', $jobs->job_name, ['class' => 'form-control', 'required' => 'required']) !!}
      @if ($errors->has('job_name'))
        <div class="alert alert-danger">
          {{ $errors->first('job_name') }}
        </div>
      @endif
    </div>
    <div class="form-group">
      <label>Публикация страницы</label>
      <div class="form-check">
        <input type="hidden" name="is_published" value="0">
        <input type="checkbox"
               class="form-check-input"
               id="is_published"
               name="is_published" {{checked_is($jobs->is_published, 'is_published', 1)}}
               value="1">
        <label class="form-check-label" for="is_published">Опликовано</label>
      </div>
    </div>
    <div class="form-group">
      <label>Описание вакансии</label>

      <reachtext
          name="job_description"
          value="{{$jobs->job_description ?? ''}}"
      ></reachtext>
      @if ($errors->has('job_description'))
        <div class="alert alert-danger">
          {{ $errors->first('job_description') }}
        </div>
      @endif
    </div>
  </div>
</div>

resources/views/admin/jobs/list.blade.php
@extends('admin/layout', [
'title' => 'Список вакансий'
])

@section('content')

  <nav class="navbar navbar-light bg-light mb-4">

    <a class="btn btn-outline-primary" href="{{route('admin.jobs.create')}}">
      <i class="fas fa-plus"></i>
      Добавить вакансию
    </a>
  </nav>

  @if(session('status'))
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      {{session('status')}}
    </div>
  @endif

  @if($jobs->count() == 0)
    <h5>Пока нет ни одной страницы</h5>
  @else
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th>Название вакансии</th>
        <th>Дейтвия</th>
      </tr>
      </thead>
      <tbody>
      @foreach($jobs as $job)
        <tr>
          <td class="article_title">
            <span>
              <a href="{{ route('admin.jobs.edit', $job->id) }}">
                {{ $job->job_name }}
              </a>
            </span>
          </td>
          <td class="actions">
            <form class="d-inline" action="{{ route('admin.jobs.update', $job->id) }}" method="post">
              @csrf
              @method('put')
              <a href="{{ route('admin.jobs.edit', $job->id) }}" class="btn btn-info btn-sm"
                 title="Редактировать">
                <i class="fas fa-edit"></i>
              </a>
            </form>
            <form class="d-inline" method="POST" action="{{route('admin.jobs.destroy', $job->id)}}">
              @csrf
              @method('DELETE')
              <a href="" class="action_delete" title="Переместить в корзину">
                <button type="submit" class="btn btn-danger btn-sm" name="delete_review"
                        value="delete">
                  <i class="fas fa-trash-alt"></i>
                </button>
              </a>
            </form>
          </td>

        </tr>
      @endforeach
      @endif
      </tbody>
    </table>

@endsection