routes/web.php
<?php

Route::get('/', 'EstateCatalogController@index')->name('index');
Route::get('/search', 'EstateCatalogController@search')->name('ad.search');
Route::get('/object-{id}', 'EstateCatalogController@showAd')->name('ad.show');

Route::get('/category/{alias}', 'EstateCatalogController@showCategory')
    ->where('alias', '[A-Za-z/-]+')
    ->name('category.show');
Route::get('/catalog/sold', 'EstateCatalogController@sold')->name('category.sold');

Route::get('/articles', 'ArticleController@index')->name('articles.index');

Route::get('/catalog/sale', function() {
    return view('site/special/sale', ['meta_title' => 'Продажа бизнеса']);
})->name('category.sale');

Route::get('/reviews', 'ReviewController@index')->name('reviews.index');
Route::get('/jobs', 'JobsController@index')->name('jobs.index');
Route::get('/jobs/{id}', 'JobsController@show')->name('jobs.show');

Route::group([
    'as' => 'special.',
], function () {
    Route::get('/modal/{key}', 'ServicePageController@showModal')->name('modal');
    Route::post('/form/{key}', 'FromHandlerController@send')->name('form.handler');

    /**
     * Special page resolved by router name
     * All special page used template from site/special/[route_name]
     */
    Route::get('/contacts', 'ServicePageController@special')->name('contacts');
    Route::get('/about-us', 'ServicePageController@special')->name('about');

    /** Business services */
    Route::get('/poluchenie-vypisok', 'ServicePageController@special')->name('extracts');
    Route::get('/poisk-biznesa', 'ServicePageController@special')->name('business-search');
    Route::get('/proverka-riskov', 'ServicePageController@special')->name('risk-check');
    Route::get('/soprovozhdenie-sdelki', 'ServicePageController@special')->name('transaction-support');
    Route::get('/registraciya-yuridicheskih-lic', 'ServicePageController@special')->name('registration-entities');

    /** Other service page */
    Route::get('/services', 'ServicePageController@special')->name('other-service');
});

Auth::routes();

/* admin management routes */

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => [
        'auth'
    ]
], function () {

    App\Http\Controllers\Admin\CustomerCallingController::route();
    App\Http\Controllers\Admin\DashboardController::route();
    App\Http\Controllers\Admin\DeclarationController::route();
    App\Http\Controllers\Admin\PlaneController::route();

    Route::resource('articles', 'ArticlesController');
    Route::resource('categories', 'CategoriesController');

    Route::resource('users', 'UsersController');
    Route::get('users/{id}/roles', 'UsersController@showRoles')->name('users.roles');
    Route::put('users/{id}/roles', 'UsersController@updateRoles')->name('users.updateRoles');

    Route::resource('roles', 'RolesController');

    //TODO: exclude show resource

    App\Http\Controllers\Admin\EstateController::route();

    Route::get('customer-calling-history/{id}/event/{event_id}', 'CustomerCallingController@editEvent')->name('customer.calling.event');
    Route::put('customer-calling-history/{id}/event/{event_id}', 'CustomerCallingController@updateEvent')->name('customer.calling.event.update');
    Route::get('customer-calling-history/{id}/event/{event_id}/delete', 'CustomerCallingController@deleteEvent')->name('customer.calling.event.delete');

    Route::get('customer-calling-history/{id}/comments', 'CustomerCallingController@comments')->name('customer.calling.comments');
    Route::post('customer-calling-history/{id}/comments', 'CustomerCallingController@addComment')->name('customer.calling.comments.add');
    Route::get('customer-calling-history/{id}/comments/{commentId}', 'CustomerCallingController@editComment')->name('customer.calling.comments.edit');
    Route::put('customer-calling-history/{id}/comments/{commentId}', 'CustomerCallingController@updateComment')->name('customer.calling.comments.update');
    Route::get('customer-calling-history/{id}/comments/{commentId}/delete', 'CustomerCallingController@deleteComment')->name('customer.calling.comments.delete');

    Route::resource('review', 'ReviewController');
    Route::resource('jobs', 'JobsController');

    App\Http\Controllers\Admin\DirectoryController::route();

    Route::get('directory/{index}/item/{id}', 'DirectoryController@item')->name('directory.item');

    Route::get('/review', 'ReviewController@index')->name('review.index');
    Route::delete('/review/{id}', 'ReviewController@destroy')->name('review.destroy');

    Route::get('/jobs', 'JobsController@index')->name('jobs.index');
    Route::get('/jobs/{id}', 'JobsController@show')->name('job.show');
    Route::get('/jobs/{id}/delete', 'JobsController@destroy')->name('jobs.destroy');

    Route::get('documents', 'DocumentsController@index')->name('documents.index');
    Route::post('documents', 'DocumentsController@upload')->name('documents.upload');
    Route::get('documents/delete', 'DocumentsController@delete')->name('documents.delete');

    Route::get('forms/', 'FormReportController@index')->name('form.index');
    Route::get('forms/{form_id}', 'FormReportController@show')->name('form.show');

    Route::get('forms/{estate}/comments', 'FormReportController@comments')->name('form.comments');
    Route::post('forms/{estate}/comments', 'FormReportController@addComment')->name('form.comments.add');
    Route::get('forms/{estate}/comments/{commentId}', 'FormReportController@editComment')->name('form.comments.edit');
    Route::put('forms/{estate}/comments/{commentId}', 'FormReportController@updateComment')->name('form.comments.update');
    Route::get('forms/{estate}/comments/{commentId}/delete', 'FormReportController@deleteComment')->name('form.comments.delete');
});

Route::get('/image/', 'ImageGeneratorController@generate');
Route::get('/image/flush', 'ImageGeneratorController@flush');

Route::post('basket', 'FileBasketController@putFile')->name('basket');
Route::delete('basket', 'FileBasketController@dropFile');

Route::get('{url}', 'ArticleController@show')->name('articles.show')
    ->where('url', '.*');

app/Article.php
<?php

namespace App;

use App\Interfaces\ReachModelI;
use App\Services\ImageGenerator;
use App\Traits\BelongsToUser;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class Article extends Model implements ReachModelI
{
    use BelongsToUser;

    protected $fillable = [
        'category_id',
        'title',
        'preview',
        'url',
        'meta_title',
        'description',
        'keywords',
        'text',
        'parent_id',
        'is_published',
    ];

    protected $fileFolder = 'articles/%s/%s';

    protected $imageFolder = null;

    protected $previewFileName = 'preview';

    protected static function boot()
    {
        static::creating(function (Model $model) {
            if (is_null($model->getAttribute('url'))) {
                $model->createUrl();
            }
        });

        static::updating(function (Model $model) {
            if (is_null($model->getAttribute('url'))) {
                $model->createUrl();
            }
        });

        parent::boot();
    }


    public function getIsPublishedAttribute()
    {
        return is_null($this->attributes['deleted_at'] ?? null) && !is_null($this->attributes['published_at'] ?? null);
    }

    public function setIsPublishedAttribute($value)
    {
        $value = (bool)$value;

        if ($this->getIsPublishedAttribute() !== $value) {
            $this->attributes['published_by'] = $value ? \Auth::user()->id : null;
            $this->attributes['published_at'] = $value ? Carbon::now() : null;
        }
    }

    public function category()
    {
        return $this->hasOne(ArticleCategory::class, 'id', 'category_id');
    }

    public function getPreviewAttribute()
    {
        $filePath = null;
        $disk = \Storage::disk();

        $globalPath = $disk->path($this->getFolder() . $this->previewFileName . '.*');
        $files = File::glob($globalPath);

        if (is_array($files)) {
            $filePath = current($files);
            $filePath = str_replace($disk->path(''), '', $filePath);
        }

        return ImageGenerator::create($filePath);
    }

    public function setPreviewAttribute($file)
    {
        $globalPath = \Storage::disk()->path($this->getFolder() . '*');
        $files = File::glob($globalPath);
        File::delete(File::glob($globalPath));

        if ($file instanceof \Illuminate\Http\UploadedFile) {
            $fileName = $this->previewFileName . '.' . $file->guessExtension();

            \Storage::disk()->putFileAs(
                $this->getFolder(),
                $file,
                $fileName
            );
        }
    }

    public function getSimilarArticles($limit = 3)
    {
        return self::limit($limit)
            ->whereNotNull('published_by')
            ->get();
    }

    public function getFolder(): string
    {
        if(is_null($this->imageFolder)){
            $level1 = floor($this->id / 1000);
            $level2 = $this->id % 1000;

            $this->imageFolder = sprintf($this->fileFolder, $level1, $level2);
            $this->imageFolder = rtrim($this->imageFolder, '/') . '/';
        }

        return $this->imageFolder;
    }

    public function createUrl()
    {
        $url = [];

        if ($categoryId = $this->getAttribute('category_id')) {
            $categoryAlias = ArticleCategory::find($categoryId)
                ->alias;

            if ($categoryAlias) {
                $url[] = $categoryAlias;
            }
        }

        $url[] = Str::slug($this->getAttribute('title'));

        array_walk($url, function (&$item) {
            $item = trim($item, '/');
        });

        $this->setAttribute('url', join('/', $url));
    }
}

app/Http/Controllers/Admin/ArticlesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Services\FileBasket;
use Auth;
use Illuminate\Database\Query\Builder;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Carbon\Carbon;

class ArticlesController extends Controller
{
    public function index(Request $request)
    {
        $meta = [
            'title' => 'Все страницы',
        ];

        /**
         * @var Builder
         */
        $articles = Article::orderBy('id', 'DESC')
            ->whereNull('deleted_by')
            ->with(['owner']);

        if ($request->has('autor')) {
            $articles->where('created_by', $request->input('author'));
        }

        if ($request->filled('category_id')) {
            $articles->whereCategoryId($request->input('category_id'));
        }

        if ($request->filled('s')) {
            $articles->where('title', 'like', '%' . $request->input('s') . '%');
        }

        $articles = $articles->paginate(20);

        return view('admin/articles/list',
            [
                'articles' => $articles,
                'counter' => $articles->firstItem(),
            ], $meta);
    }

    public function create(Request $request)
    {
        $meta = [
            'title' => 'Добавление новой страницы',
            'article' => $request,
        ];

        return view('admin/articles/create', $meta);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'text' => 'required',
        ]);

        $article = new Article($request->all());

        $article->save();

        return redirect(route('admin.articles.edit', [
            'id' => $article->id
        ]))->with('status', 'Страница сохранена');
    }

    public function edit($id)
    {
        $article = Article::findOrFail($id);

        $meta = [
            'title' => 'Редактирование страницы ' . $article->title,
        ];

        return view('admin/articles/edit', compact('article'), $meta);
    }

    public function update(Request $request, $id)
    {
        $article = Article::findOrFail($id);

        if ($request->delete_article == 'delete') {
            $article->deleted_by = Auth::user()->id;
            $article->deleted_at = Carbon::now();

            $article->save();
            return redirect()->back()->with('status', 'Страница перемещена в корзину.');
        }

        $this->validate($request, [
            'title' => 'required',
            'text' => 'required',
        ]);

        $article->fill($request->all());

        $article->save();

        if ($request->has('preview')) {
            $article->preview = $request->file('preview');
        } elseif ($request->filled('remove_preview')) {
            $article->preview = null;
        }

        return redirect(route('admin.articles.edit', [
            'id' => $article->id
        ]))->with('success', 1);
    }

    public function destroy($id)
    {
        //TODO: need add destroy article action
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\ArticleCategory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::whereNotNull('published_by')
            //->whereCategoryId(env('ARTICLE_CATEGORY', 1))
            ->paginate(12);

        return view('site/articles/list', [
            'articles' => $articles
        ]);
    }

    public function show($alias)
    {
        $template = 'site/articles/article';

        $article = Article::whereUrl($alias)->with(['category'])
            ->whereNotNull('published_by')
            ->firstOrFail();

        /**
         * @var ArticleCategory;
         */
        $category = $article->category;

        if ($category && $category->template) {
            $template = 'site/articles/templates/' . $category->template;
        }

        return view($template, [
            'article' => $article
        ]);
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin/layout', [
'title' => 'Добавить страницу'
])

@section('content')
  @if(session('status'))
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      {{session('status')}}
    </div>
  @endif

  <form action="{{ route('admin.articles.store') }}" method="post">
    @csrf
    @method('post')

    @include('admin/articles/form', ['article' => $article])

    <button type="submit" class="btn btn-success">Сохранить</button>
  </form>
@stop

resources/views/admin/articles/edit.blade.php
@extends('admin/layout')

@section('content')

  @if(session('status'))
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      {{session('status')}}
    </div>
  @endif

  {!! Form::model($article, ['files' => true, 'route' => ['admin.articles.update', $article->id], 'method'=>'PUT']) !!}

  @include('admin/articles/form', ['article' => $article])

  <button type="submit" class="btn btn-success">Сохранить</button>

  {!! Form::close() !!}

@stop

resources/views/admin/articles/form.blade.php
<div class="row">
  <div class="col-9">

    <div class="form-group">
      <label>Название *</label>
      <input type="text" class="form-control" name="title" value="{{old('title', $article->title)}}" required>
      @if ($errors->has('title'))
        <div class="alert alert-danger">
          {{ $errors->first('title') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <label>Группа статей</label>
      @include('/admin/parts/directory', [
        'name' => 'category_id',
         'directoryIndex' => 'article_category',
         'value' => $article->category_id ?? 'null'
      ])
    </div>

    <div class="form-group">
      <label>Ссылка</label>
      <input type="text" class="form-control" name="url" value="{{old('url', $article->url)}}">
      @if ($errors->has('url'))
        <div class="alert alert-danger">
          {{ $errors->first('url') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <label>Мета заголовок (тег title)</label>
      <input type="text" class="form-control" name="meta_title" value="{{old('meta_title', $article->meta_title)}}">
      @if ($errors->has('meta_title'))
        <div class="alert alert-danger">
          {{$errors->first('meta_title')}}
        </div>
      @endif
    </div>

    <div class="form-group">
      <label>Описание (meta_description)</label>
      <input type="text" class="form-control" name="description"
             value="{{ $article->description ?? old('description') }}">
      @if ($errors->has('description'))
        <div class="alert alert-danger">
          {{ $errors->first('description') }}
        </div>
      @endif
    </div>

    <div class="form-group">
      <label>Ключевые слова (meta_keywords)</label>
      <input type="text" class="form-control" name="keywords" value="{{ $article->keywords ?? old('keywords') }}">
      @if ($errors->has('keywords'))
        <div class="alert alert-danger">
          {{ $errors->first('keywords') }}
        </div>
      @endif
    </div>

  </div>
  <div class="col-3">

    <div class="form-group">
      <label>Заголовочное изображение</label>
      <br>
      @if($article instanceof App\Article)
        <img src="{{$article->preview->getWidth(400)}}" alt="" class="img-thumbnail mb-4">
      @endif
      <input type="file" class="form-control" name="preview">

      Удалить {{Form::checkbox('remove_preview')}}
    </div>

  </div>
</div>

<div class="form-group">
  <label>Публикация страницы</label>
  <div class="form-check">
    <input type="hidden" name="is_published" value="0">
    <input type="checkbox"
           class="form-check-input"
           id="is_published"
           name="is_published" {{checked_is($article->is_published, 'is_published', 1)}}
           value="1">
    <label class="form-check-label" for="is_published">Опубликовано</label>
  </div>
</div>

<div class="form-group">
  <reachtext
      name="text"
      value="{{  old('text', $article->text ?? '') }}"
  ></reachtext>
  @if ($errors->has('text'))
    <span class="help-block">
                                    <strong>{{ $errors->first('text') }}</strong>
                                </span>
  @endif
</div>

resources/views/admin/articles/list.blade.php
@extends('admin/layout')

@section('content')

  <nav class="navbar navbar-light bg-light mb-4">
    <a class="btn btn-outline-primary" href="{{ route('admin.articles.create') }}">
      <i class="fas fa-plus"></i> Добавить страницу
    </a>
    {!! Form::model(request(), ['class' => 'form-inline d-block', 'method' => 'GET']) !!}
    {!! Form::select('category_id',
['' => 'Все категории'] +
                    \App\ArticleCategory::all()->pluck('title', 'id')->toArray(),
                    null, [
                        'class' => 'form-control mr-2',
                        'style' => 'width: 320px'
                    ]) !!}
    {!! Form::text('s', null, ['class'=>'form-control mr-2', 'placeholder' => 'Поиск']) !!}
    <button class="btn btn-outline-success my-2 my-sm-0">Найти</button>
    {!! Form::close() !!}
  </nav>

  @if(session('status'))
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      {{session('status')}}
    </div>
  @endif

  @if($articles->count() == 0)
    <h5>Ничего не найдено</h5>
  @else
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th>№</th>
        <th>Название</th>
        <th>Автор</th>
        <th>Публикация</th>
        <th>Действия</th>
      </tr>
      </thead>
      <tbody>
      @foreach($articles as $article)
        <tr>
          <td>{{ $counter++ }}</td>
          <td class="article_title">

            <a href="{{ route('admin.articles.edit', $article->id) }}">
              {{ $article->title }}
            </a>

            <a href="{{ url($article->url) }}" target="_blank" class="btn btn-light btn-sm"
               title="Подробнее">
              <i class="fas fa-eye"></i>
            </a>

          </td>
          <td>
            @if($article->owner->name ?? null)
              <a href="{{ route('admin.articles.index', ['author' => $article->created_by]) }}">
                {{ $article->owner->name}}
              </a>
            @endif
          </td>
          <td class="published">
            @if($article->published_at)
              {{ $article->published_at }}
            @else
              <div class="text-muted">Не опубликована</div>
            @endif
          </td>
          <td class="actions">
            <form action="{{ route('admin.articles.update', $article->id) }}" method="post">
              @csrf
              @method('put')
              <a href="{{ route('admin.articles.edit', $article->id) }}" class="btn btn-info btn-sm"
                 title="Редактировать">
                <i class="fas fa-edit"></i>
              </a>
              <a href="" class="action_delete" title="Переместить в корзину">
                <button type="submit" class="btn btn-danger btn-sm" name="delete_article"
                        value="delete">
                  <i class="fas fa-trash-alt"></i>
                </button>
              </a>
            </form>
          </td>

        </tr>
      @endforeach
      @endif
      </tbody>
    </table>
    {{  $articles->links() }}
@stop