routes/web.php
<?php

Route::get('/', 'EstateCatalogController@index')->name('index');
Route::get('/search', 'EstateCatalogController@search')->name('ad.search');
Route::get('/object-{id}', 'EstateCatalogController@showAd')->name('ad.show');

Route::get('/category/{alias}', 'EstateCatalogController@showCategory')
    ->where('alias', '[A-Za-z/-]+')
    ->name('category.show');
Route::get('/catalog/sold', 'EstateCatalogController@sold')->name('category.sold');

Route::get('/articles', 'ArticleController@index')->name('articles.index');

Route::get('/catalog/sale', function() {
    return view('site/special/sale', ['meta_title' => 'Продажа бизнеса']);
})->name('category.sale');

Route::get('/reviews', 'ReviewController@index')->name('reviews.index');
Route::get('/jobs', 'JobsController@index')->name('jobs.index');
Route::get('/jobs/{id}', 'JobsController@show')->name('jobs.show');

Route::group([
    'as' => 'special.',
], function () {
    Route::get('/modal/{key}', 'ServicePageController@showModal')->name('modal');
    Route::post('/form/{key}', 'FromHandlerController@send')->name('form.handler');

    /**
     * Special page resolved by router name
     * All special page used template from site/special/[route_name]
     */
    Route::get('/contacts', 'ServicePageController@special')->name('contacts');
    Route::get('/about-us', 'ServicePageController@special')->name('about');

    /** Business services */
    Route::get('/poluchenie-vypisok', 'ServicePageController@special')->name('extracts');
    Route::get('/poisk-biznesa', 'ServicePageController@special')->name('business-search');
    Route::get('/proverka-riskov', 'ServicePageController@special')->name('risk-check');
    Route::get('/soprovozhdenie-sdelki', 'ServicePageController@special')->name('transaction-support');
    Route::get('/registraciya-yuridicheskih-lic', 'ServicePageController@special')->name('registration-entities');

    /** Other service page */
    Route::get('/services', 'ServicePageController@special')->name('other-service');
});

Auth::routes();

/* admin management routes */

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => [
        'auth'
    ]
], function () {

    App\Http\Controllers\Admin\CustomerCallingController::route();
    App\Http\Controllers\Admin\DashboardController::route();
    App\Http\Controllers\Admin\DeclarationController::route();
    App\Http\Controllers\Admin\PlaneController::route();

    Route::resource('articles', 'ArticlesController');
    Route::resource('categories', 'CategoriesController');

    Route::resource('users', 'UsersController');
    Route::get('users/{id}/roles', 'UsersController@showRoles')->name('users.roles');
    Route::put('users/{id}/roles', 'UsersController@updateRoles')->name('users.updateRoles');

    Route::resource('roles', 'RolesController');

    //TODO: exclude show resource

    App\Http\Controllers\Admin\EstateController::route();

    Route::get('customer-calling-history/{id}/event/{event_id}', 'CustomerCallingController@editEvent')->name('customer.calling.event');
    Route::put('customer-calling-history/{id}/event/{event_id}', 'CustomerCallingController@updateEvent')->name('customer.calling.event.update');
    Route::get('customer-calling-history/{id}/event/{event_id}/delete', 'CustomerCallingController@deleteEvent')->name('customer.calling.event.delete');

    Route::get('customer-calling-history/{id}/comments', 'CustomerCallingController@comments')->name('customer.calling.comments');
    Route::post('customer-calling-history/{id}/comments', 'CustomerCallingController@addComment')->name('customer.calling.comments.add');
    Route::get('customer-calling-history/{id}/comments/{commentId}', 'CustomerCallingController@editComment')->name('customer.calling.comments.edit');
    Route::put('customer-calling-history/{id}/comments/{commentId}', 'CustomerCallingController@updateComment')->name('customer.calling.comments.update');
    Route::get('customer-calling-history/{id}/comments/{commentId}/delete', 'CustomerCallingController@deleteComment')->name('customer.calling.comments.delete');

    Route::resource('review', 'ReviewController');
    Route::resource('jobs', 'JobsController');

    App\Http\Controllers\Admin\DirectoryController::route();

    Route::get('directory/{index}/item/{id}', 'DirectoryController@item')->name('directory.item');

    Route::get('/review', 'ReviewController@index')->name('review.index');
    Route::delete('/review/{id}', 'ReviewController@destroy')->name('review.destroy');

    Route::get('/jobs', 'JobsController@index')->name('jobs.index');
    Route::get('/jobs/{id}', 'JobsController@show')->name('job.show');
    Route::get('/jobs/{id}/delete', 'JobsController@destroy')->name('jobs.destroy');

    Route::get('documents', 'DocumentsController@index')->name('documents.index');
    Route::post('documents', 'DocumentsController@upload')->name('documents.upload');
    Route::get('documents/delete', 'DocumentsController@delete')->name('documents.delete');

    Route::get('forms/', 'FormReportController@index')->name('form.index');
    Route::get('forms/{form_id}', 'FormReportController@show')->name('form.show');

    Route::get('forms/{estate}/comments', 'FormReportController@comments')->name('form.comments');
    Route::post('forms/{estate}/comments', 'FormReportController@addComment')->name('form.comments.add');
    Route::get('forms/{estate}/comments/{commentId}', 'FormReportController@editComment')->name('form.comments.edit');
    Route::put('forms/{estate}/comments/{commentId}', 'FormReportController@updateComment')->name('form.comments.update');
    Route::get('forms/{estate}/comments/{commentId}/delete', 'FormReportController@deleteComment')->name('form.comments.delete');
});

Route::get('/image/', 'ImageGeneratorController@generate');
Route::get('/image/flush', 'ImageGeneratorController@flush');

Route::post('basket', 'FileBasketController@putFile')->name('basket');
Route::delete('basket', 'FileBasketController@dropFile');

Route::get('{url}', 'ArticleController@show')->name('articles.show')
    ->where('url', '.*');

resources/views/site/parts/ad-card.blade.php
<div class="col-lg-4 col-md-6 col-sm-6 col-12 mb-4">
  <div class="card-ready-business border">
    <a class="preview-ready-business" href="{{route('ad.show', $ad->id)}}">
      <img alt="" class="pic-business" src="{{$ad->getPreview()->getSize(359, 139)}}">
    </a>
    <div class="info-ready-business">
      <a class="title-ready-business" href="{{route('ad.show', $ad->id)}}">
        {{$ad->estate->title ?: $ad->estate->object_title}}
      </a>
      <span class="price-ready-business mb-2">@money($ad->price) ₽</span>
      <span class="profit-ready-business mb-2">Прибыль: @money($ad->profit) ₽/мес</span>
      <div>
        <span class="city-ready-business">{{$ad->region}}</span>
        {{--
        <span class="date-ready-business">{{$ad->created_at->format('Y-m-d')}}</span>
        --}}
      </div>
    </div>
  </div>
</div>

resources/views/site/parts/article-card.blade.php
<div class="col-12 col-lg-4 col-md-6 col-sm-6">
  <div class="article-card">
    <a href="{{route('articles.show', ['url' => $article->url])}}">
      <img class="article-card__preview" alt="" src="{{$article->preview->getSize(360, 207)}}">
    </a>
    <a href="{{route('articles.show', ['url' => $article->url])}}"
       class="article-card__title">{{$article->title}}</a>
  </div>
</div>

resources/views/site/parts/category-card.blade.php
<div class="col-md col-md-3">
  <div class="card-business mr-4 mb-4">
    <div class="categories-business mb-2">
      <a class="name-business" href="{{route('category.show', $category->alias)}}">{{$category->title}}
        <sup class="counter-business">{{$category->ad_counters}}</sup></a>
    </div>
    <span class="price-from-business">от {{$category->min_price}} ₽</span>
  </div>
</div>

resources/views/site/parts/header.blade.php
<div class="page-header">
  <div class="container">
    <h1 class="page-header__title">{{$title ?? $meta_title}}</h1>

    <div class="breadcrumb-b">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link-previous" href="/">Главная</a>
          <span class="point"></span>
        </li>
        @foreach($links ?? [] as $link)
          <li class="nav-item">
            <a class="nav-link-previous" href="{{$link['url']}}">{{$link['title']}}</a>
          </li>
        @endforeach
        <li class="nav-item">
          <span class="nav-link">{{$current_title ?? $title ?? $meta_title}}</span>
        </li>
      </ul>
    </div>

  </div>
</div><!-- title-page -->

resources/views/site/parts/help-for-business.blade.php
<div class="help-for-business">
  <div class="container">
    <h3 class="title-business">Всегда готовы помочь</h3>

    <div class="row">

      <div class="col-lg-4 col-md-4 col-sm-6">
        <a class="help-card mix--briefcase" href="{{route('special.extracts')}}">
          <div class="help-description">Получение выписок из ЕГРЮЛ,ЕГРИП</div>
          <div class="help-price">500 ₽</div>
        </a>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-6">
        <a class="help-card mix--graph" href="{{route('special.business-search')}}">
          <div class="help-description">Эксклюзивный поиск бизнеса под запрос покупателя</div>
          <div class="help-price">Бесплатно</div>
        </a>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-6">
        <a class="help-card mix--secure-shield" href="{{route('special.risk-check')}}">
          <div class="help-description">Проверка рисков покупаемого бизнеса</div>
          <div class="help-price">от 25 000 ₽</div>
        </a>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-6">
        <a class="help-card mix--legal-document" href="{{route('special.transaction-support')}}">
          <div class="help-description">Сопровождение сделок купли продажи бизнеса</div>
          <div class="help-price">от 25 000 ₽</div>
        </a>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-6">
        <a class="help-card mix--file" href="{{route('special.registration-entities')}}">
          <div class="help-description">Регистрация юридических лиц</div>
          <div class="help-price">от 20 000 ₽</div>
        </a>
      </div>

      @if($call_btn ?? true === true)

        <div class="col-lg-4 col-md-4 col-sm-6">
          <div class="help-card-request" data-href="{{route('special.modal', 'callback')}}" data-modal>
            <span class="help-label d-inline-flex justify-content-center align-items-end">
              <span class="help-request">Оставить заявку</span>
              <div class="help-request-icon mb-2">
              </div>
            </span>
          </div>
        </div>

      @endif

    </div>
  </div>
</div> <!-- help-for-business -->

resources/views/site/parts/pagination.blade.php
@if ($paginator->hasPages())
  <div class="pagination-list">
    <div class="container">
      <div class="row">
        <div class="col-md col-sm">
          <nav>
            <ul class="pagination">
              {{-- Pagination Elements --}}
              @foreach ($elements as $element)
                {{-- "Three Dots" Separator --}}
                @if (is_string($element))
                  <li class="page-item dots-page-item">
                    <span class="page-link dots-page-item">...</span>
                  </li>
                @endif

                {{-- Array Of Links --}}
                @if (is_array($element))
                  @foreach ($element as $page => $url)
                    @if ($page == $paginator->currentPage())
                      <li class="page-item" aria-current="page">
                        <span class="page-link active-item">{{ $page }}</span>
                      </li>
                    @else
                      <li class="page-item">
                        <a class="page-link" href="{{ $url }}">{{ $page }}</a>
                      </li>
                    @endif
                  @endforeach
                @endif
              @endforeach
            </ul>
          </nav>
        </div>
        <div
            class="col-md col-sm-12 d-flex justify-content-sm-center justify-content-center justify-content-lg-end justify-content-md-end">
          <nav>
            <ul class="pagination">
              <li class="page-item">
              @if ($paginator->onFirstPage())
                <li class="page-item" aria-disabled="true">
                  <span class="page-link page-link--prev" aria-hidden="true">Назад</span>
                </li>
              @else
                <li class="page-item">
                  <a class="page-link page-link--prev" href="{{ $paginator->previousPageUrl() }}" rel="prev">Назад</a>
                </li>
              @endif
              <li class="page-item">
                <span class="page-link">|</span>
              </li>

              {{-- Next Page Link --}}
              @if ($paginator->hasMorePages())
                <li class="page-item">
                  <a class="page-link page-link--next" href="{{ $paginator->nextPageUrl() }}" rel="next">Далее</a>
                </li>
              @else
                <li class="page-item" aria-disabled="true">
                  <span class="page-link page-link--next" aria-hidden="true">Далее</span>
                </li>
              @endif
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div><!-- pagination-list -->
@endif

resources/views/site/parts/request-form.blade.php
<div class="form mix-job-request">
  <div class="form__title">
    {{$request_form_title ?? 'Запрос на продажу бизнеса'}}
  </div>
  <form action="{{route('special.form.handler', 'sale_request')}}"
        method="POST"
        enctype="multipart/form-data"
        data-module="Form"
  >
    <input type="hidden" name="form_source" value="{{$request_form_title ?? 'Запрос на продажу бизнеса'}}">
    <div class="row">
      <div class="col-md-6 form-group">
        <input placeholder="Фамилия Имя Отчество" class="form-control" name="name">
      </div>
      <div class="col-md-6 form-group">
        <input placeholder="Телефон" class="form-control" name="phone">
      </div>
      <div class="col-md-6 form-group">
        <input placeholder="E-mail" class="form-control" name="email">
      </div>
      <div class="col-md-6 form-group">
        <button class="btn btn-block btn-primary" type="submit">Отправить</button>
      </div>
    </div>
  </form>

  <div class="personal-data-processing">
    Нажимая на кнопку "Отправить", вы даете согласие на
    <a href="#">обработку своих персональных данных</a>
  </div>
</div> <!-- form -->

resources/views/site/parts/special-menu.blade.php
<div class="special-menu">
  <ul class="nav flex-column">
    <li class="nav-item {{classActiveRoute('special.about', 'active-item')}}">
      <a class="nav-link" href="{{route('special.about')}}">О компании</a>
    </li>
    <li class="nav-item {{classActiveController('JobsController', 'active-item')}}">
      <a class="nav-link" href="{{route('jobs.index')}}">Вакансии</a>
    </li>
    <li class="nav-item {{classActiveController('ReviewController', 'active-item')}}">
      <a class="nav-link" href="{{route('reviews.index')}}">Отзывы</a>
    </li>
  </ul>
</div>